name: vEMTools

channels:
  - conda-forge
      
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - pandas
  - opencv
  - joblib
  - matplotlib-base
  - pyyaml
  - pip
  - pip:
    - napari[all]
    - napari-ome-zarr
    - ome-zarr